# base image
FROM node:12.16.1-alpine3.11 as build

ADD . /app
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

#RUN npm install && \
#	NG_CLI_ANALYTICS=ci npm install -g @angular/cli@9.0.2
RUN npm install
RUN NG_CLI_ANALYTICS=ci npm install -g @angular/cli@9.0.2

# run tests
# RUN ng test --watch=false
# RUN ng e2e --port 4202
RUN ng build --configuration=production --output-path=dist

############
### prod ###
############

# base image
FROM nginx:1.17.8-alpine

# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]
