# base image
FROM node:12.16.1-alpine3.11

ADD . /app
WORKDIR /app

# install and cache app dependencies
RUN npm config set strict-ssl false && \
	npm install && \
	NG_CLI_ANALYTICS=ci npm install -g @angular/cli@9.0.2

EXPOSE 4200 49153

# start app
CMD ng serve --host 0.0.0.0
