version: "3.7"
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Docker/Dockerfile-dev
    ports:
    - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
  frontend:
    build:
      context: ./Frontend
      dockerfile: Docker/Dockerfile-dev
    ports:
    - "4200:4200"
    - "49153:49153"
    environment:
      - CHOKIDAR_USEPOLLING=true
