POST http://localhost:5000/forecast/ HTTP/1.1
content-type: application/json

{
    "data": [1, 2, 3, 4, 5, 6],
    "n_periods": 4,
    "alpha": 0.05
}

###

POST http://localhost:5000/forecast/ HTTP/1.1
content-type: application/json

{
    "data": [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12],
        [13, 14, 15]
    ],
    "columns": ["Serie1", "Serie2", "Serie3"]
}
